# 서버설정
server:
  port: 8088
  servlet:
    session:
      tracking-modes: cookie
  # 에러페이지
  error:
    # Exception 포함여부
    include-exception: true
    # message 포함여부
    include-message: never
    # trace 포함여부
    include-stacktrace: never
    # errors 포함여부
    include-binding-errors: never


# 스프링 환경설정
spring:
  # MVC
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  # DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pptor?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull&connectTimeout=60
    username: team
    password: two

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      open-in-view: true

  # 메세지
  messages:
    basename: messages, config/i18m/messages, errors

  # 타임리프
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    cache: false
    mvc:
      static-path-pattern: "/static/**"

  # 이메일
  mail:
    host: smtp.gmail.com
    port: 587
    username: "구글메일"  # 둘다 "" 안쪽에 써주시면 됩니다.
    password: "구글토큰"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # 로거
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
